version: '3.8'
services:
  bot:
    build: .
    container_name: capitol_tracker_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot_data.db:/app/bot_data.db
      - ./bot_data.db.bak:/app/bot_data.db.bak
